<?php

use Drupal\Component\Utility\Html;
use \Drupal\Core\Form\FormStateInterface;

	

function form_in_sms_form_alter(&$form, FormStateInterface $form_state) {
    $form['actions']['submit']['#submit'][]  = 'form_in_sms_form_submit';
}

function form_in_sms_form_submit($form, FormStateInterface $form_state) {
 /*
require_once 'lib/sms.ru.php';

$smsru = new SMSRU(''); // Ваш уникальный программный ключ, который можно получить на главной странице

$data = new stdClass();
$data->to = '';
$data->text = $form['field_nomer_telefona']['widget']['0']['value']['#value'] .' '.$form['name']['#value'] ; // Текст сообщения
// $data->from = ''; // Если у вас уже одобрен буквенный отправитель, его можно указать здесь, в противном случае будет использоваться ваш отправитель по умолчанию
// $data->time = time() + 7*60*60; // Отложить отправку на 7 часов
// $data->translit = 1; // Перевести все русские символы в латиницу (позволяет сэкономить на длине СМС)
// $data->test = 1; // Позволяет выполнить запрос в тестовом режиме без реальной отправки сообщения
// $data->partner_id = '1'; // Можно указать ваш ID партнера, если вы интегрируете код в чужую систему
$sms = $smsru->send_one($data); // Отправка сообщения и возврат данных в переменную

if ($sms->status == "OK") { // Запрос выполнен успешно
	\Drupal::logger('form_in_sms')->notice( "Сообщение отправлено успешно. ID сообщения: $sms->sms_id.") ;
    
} else {
	\Drupal::logger('form_in_sms')->error( "Сообщение не отправлено. Код ошибки: $sms->status_code. Текст ошибки: $sms->status_text.") ;
}
*/
 //dpm($form['actions']);
 //dpm($form['name']['#value']);
}


